/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.charneykaye.electron_java_demo;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
